name: Bot Auto Run SPK

on:
  schedule:
    - cron: '0 0 * * *' # Otomatis jalan setiap jam 12 malam
  workflow_dispatch:     # Tombol untuk menjalankan manual kapan saja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot SCM
        env:
          # Mengambil data dari Settings > Secrets yang Anda buat
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL_SCM: ${{ secrets.EMAIL_SCM }}
          PASS_SCM: ${{ secrets.PASS_SCM }}
        run: python main.py
